name: 'Deploy to GitHub Pages'

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint-check:
    name: Lint Check
    uses: ./.github/workflows/lint.yml

  deploy:
    needs: [lint-check]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Build and deploy to GitHub Pages
    outputs:
      dist: ${{ steps.upload-dist.outputs.dist }} # path to dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/cache

      - name: Build app
        run: yarn predeploy

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload dist
        id: upload-dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
            package.json

      - name: Output dist
        run: |
          echo "Uploaded dist - ${{ env.GITHUB_TOKEN }}"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
