name: 'Deploy to GitHub Pages'

on:
  push:
    branches:
      - master
      - gh-pages
  workflow_dispatch:

jobs:
  lint-check:
    name: Lint Check
    uses: ./.github/workflows/lint.yml

  build:
    needs: [lint-check]
    name: Build app
    outputs:
      dist: ${{ steps.upload-dist.outputs.dist }} # path to dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/cache

      - name: Build app
        run: yarn predeploy

      - name: Upload dist
        id: upload-dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
            package.json

      - name: Output dist
        run: echo ${{ steps.upload-dist.outputs.dist }}

  deploy:
    needs: [build]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/cache

      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      # - name: Run Deploy
      #   run: yarn deploy:gh
