name: 'Code Quality Check'

on:
  push:
    branches:
      - master
      - gh-pages
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Node setup
      #   uses: actions/setup-node@v4
      #   with:
      #     cache: 'yarn'
      #     node-version: 20

      # - name: Install dependencies
      #   run: yarn install --immutable
      - name: Checkout code and install dependencies
        uses: ./.github/actions/cache

      - name: Run format and lint
        run: yarn cq
